server:
  port: 4200

spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5331/customer_database
    username: customer_admin
    password: customer_password
    driver-class-name: org.postgresql.Driver
